workflows:
  android-apk:
    name: Bensalman APK
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Unzip
        script: |
          unzip -o bensalman-mesh-complet.zip
      - name: Deps
        script: |
          cd bensalman-mesh-complet
          flutter pub get
      - name: Build APK
        script: |
          cd bensalman-mesh-complet
          flutter build apk --release
    artifacts:
      - bensalman-mesh-complet/build/app/outputs/flutter-apk/*.apk
